# flask + mysql + myadmin
version: "3.8"

services:
  flask:
    build:
      context: ./flask
      dockerfile: dockerfile
    environment:
      - MYSQL_HOST=mysql-server
    networks:
      - devenv-network
    ports:
      - ${FLASK_PORT}:5000
    depends_on:
      - mysql-server
    links:
      - mysql-server
    restart: always
    env_file:
      - .env
    volumes:
      - ./code:/code
    # run app.py
    command: /bin/bash -c "cd code; flask run -h 0.0.0.0;"

  mysql-server:
    image: mysql:8.3
    networks:
      - devenv-network
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env
    environment:
      # set root password
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      # create database
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${MYADMIN_PORT}:80
    env_file:
      - .env
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: always
    depends_on:
      - mysql-server
    networks:
      - devenv-network

networks:
  devenv-network:
    ipam:
      driver: default
