# flask + mysql + myadmin
version: "3.8"

services:
  flask:
    build:
      context: ./flask
      dockerfile: dockerfile
    env_file:
      - .env
    networks:
      - devenv-network
    ports:
      - ${FLASK_PORT}:5000
    depends_on:
      - mysql-server
    links:
      - mysql-server
    restart: always

    volumes:
      - ./code:/code
    # run app.py
    command: /bin/bash -c "cd code; flask run -h 0.0.0.0;"

  mysql-server:
    image: mysql:8.3
    networks:
      - devenv-network
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env

  myadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    ports:
      - ${MYADMIN_PORT}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: always
    depends_on:
      - mysql-server
    networks:
      - devenv-network

  redis:
    image: redis:7.2.4-alpine3.19
    env_file:
      - .env
    restart: always
    networks:
      - devenv-network

networks:
  devenv-network:
    ipam:
      driver: default
